language: generic 

sudo: required
services: 
  - docker

before_install:
  - docker build -t mazzonig/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mazzonig/docker-react npm run test -- --coverage